- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-0c166134bc5100902
    security_group: sg-061fd314500b76b77
    ami_id: ami-09c813fb71547fc4f
    instance_type: t2.micro
    instances:
      - mysql
      - frontend
      - backend
  tasks:
    - name: install AWS boto3 and botocore
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
        - boto3
        - botocore

    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
      loop: "{{ instances }}"
