- name: Install nginx
  hosts: web
  become: yes # Elevate privileges to perform installation
  tasks:
    - name: Install nginx package
      ansible.builtin.dnf:
        name: nginx
        state: installed
      when: ansible_os_family == "RedHat"

    - name: Install nginx package
      ansible.builtin.apt:
        name: nginx
        state: installed
      when: ansible_os_family == "Debian"
